# https://dystroy.org/bacon/config/
default_job = "clippy"

[jobs.check]
command = ["cargo", "check", "--workspace", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
  "cargo",
  "clippy",
  "--workspace",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
]
need_stdout = false

[jobs.test]
command = [
  "cargo",
  "nextest",
  "run",
  "--workspace",
  "--color",
  "always",
  "--hide-progress-bar",
  "--failure-output",
  "final",
]
need_stdout = true
analyzer = "nextest"

[jobs.doc]
command = ["cargo", "doc", "--workspace", "--no-deps", "--color", "always"]
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[keybindings]
c = "job:clippy"
t = "job:test"
r = "job:run"
